### ISSUE TITLE
Some errors during running 

### ISSUE THREAD

**Issue by Huang-XN** [timkartar/DeepPBS#9] opened 2024-09-05 03:42 UTC
Hi there,

I have seen two errors while running deepPBS on my own dataset.
The input was derived from  RoseTTAFoldNA.

First error appeared on running `./process_and_predict.sh`.
Error was `Fontconfig error: Cannot load default config file: No such file: (null)`

Second error was on running visualization. 
It was ```Error: unsupported file type: 
 Error: Argument processing aborted due to exception (above).```

Second error occurred for the example data as well. 

Hope you could help me fix it.

Thanks.

**Comment by timkartar** [comment] 2024-09-05 04:34
Hi ! I am not sure if it as DeepPBS error, it seems to me that your matplotlib package might not be able to access some system fonts. Maybe this might help : https://askubuntu.com/questions/492033/fontconfig-error-cannot-load-default-config-file .

The second error looks like a pymol error, which is ok. It still saves the .pse file which you can open.

If this or similar discussions doesn't help and you want me to trouble shoot it, then I suggest you provide me with the pdb file and the full error log.

**Comment by Huang-XN** [comment] 2024-09-05 07:16
Thanks for your reply. 
The pdb file I used was in the attachment.
[model_00.zip](https://github.com/user-attachments/files/16885449/model_00.zip)

**Comment by timkartar** [comment] 2024-09-05 07:39
I just ran your file on the webserver and it executed totally fine.

See here :
https://deeppbs.usc.edu/link/172552130082

I am closing this issue as not reproducible. 

I think the only help i can provide in this is that the first issue is something about your system fonts that  you have to unfortunately figure out and the second issue is not a problem and the pse file will still be saved which you can open with pymol.

**Closed as completed by timkartar** 2024-09-05 07:39 UTC

**Comment by Huang-XN** [comment] 2024-09-05 16:03
Thank you
